// Code generated by "stringer -type NameType -linecomment -output name_type_string.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NameTypeName-1]
	_ = x[NameTypeSurname-2]
	_ = x[NameTypePatronymic-3]
}

const _NameType_name = "namesurnamepatronymic"

var _NameType_index = [...]uint8{0, 4, 11, 21}

func (i NameType) String() string {
	i -= 1
	if i < 0 || i >= NameType(len(_NameType_index)-1) {
		return "NameType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _NameType_name[_NameType_index[i]:_NameType_index[i+1]]
}
